language: python

python:
  - 3.8
  - 3.9
  - "3.10"

env:
  - DJANGO_VERSION="Django>=3.2,<4"
  - DJANGO_VERSION="Django>=4.1,<4.2"
  - DJANGO_VERSION="Django>=4.2,<5"

install:
  - pip install pyquery
  - pip install -q $DJANGO_VERSION
  - pip install coverage

script: coverage run quicktest.py multi_email_field.tests

after_success:
 - pip install coveralls
 - coveralls

# We need to exclude old versions of Python for tests with Django >= 2
matrix:
    exclude:
        - python: 2.7
          env: DJANGO_VERSION="Django>=2.0,<3"
        - python: 2.7
          env: DJANGO_VERSION="Django>=3.0,<4"
