name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
        django-version:
          - "Django>=3.2,<4"
          - "Django>=4.1,<4.2"
          - "Django>=4.2,<5"


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: |
          pip install pyquery coverage ${{ matrix.django-version }}
      - name: Run Tests
        run: |
          python quicktests.py multi_email_field.tests

  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Check quality
        run: |
          black --check .
          ruff check .
